version: "3.8"

services:
  frontend:
    image: node:latest
    # environment:
    ports:
      - 5173:5173
      - 24678:24678
    volumes:
      - ./frontend:/app
      # - ./frontend/node_modules:/app/node_modules
      # - ./frontend/src:/app/src
      # - ./frontend/static:/app/static
      # - ./frontend/vite.config.ts:/app/vite.config.ts
      # - ./frontend/svelte.config.js:/app/svelte.config.js
      # - ./frontend/package.json:/app/package.json
      # - ./frontend/tailwind.config.js:/app/tailwind.config.js
      # - ./frontend/tsconfig.json:/app/tsconfig.json
      # - ./frontend/postcss.config.js:/app/postcss.config.js
    depends_on:
      - backend
      # already installed node_modules with dev container, and bind mount, dont change it again
      # without npm install because svelte current bug are buggy with npm install with current version
    command: >
      sh -c "cd app/ && npm run dev -- --host --port 5173"
    networks:
      - frontend-backend

  backend:
    build:
      context: pocketbase
      dockerfile: Dockerfile
    # environment:
    ports:
      - "8080:8080"
    volumes:
      - ./pb_data:/pb/pb_data
    networks:
      - frontend-backend
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - frontend-backend
networks:
  frontend-backend:
    driver: bridge
